# MegaLinter Configuration for Prettier-Plugin-Powershell
# https://megalinter.io/latest/config-file/

# Apply fixes automatically
APPLY_FIXES: all

DISABLE_LINTERS:
  - SPELL_CSPELL
  - SPELL_MISSPELL
  - COPYPASTE_JSCPD

# PowerShell specific settings
POWERSHELL_POWERSHELL_CONFIG_FILE: PSScriptAnalyzerSettings.psd1
POWERSHELL_POWERSHELL_FILTER_REGEX_EXCLUDE: '(Scripts/.*\.ps1)'

# Markdown settings
MARKDOWN_MARKDOWNLINT_CONFIG_FILE: .markdownlint.json
MARKDOWN_MARKDOWNLINT_FILTER_REGEX_EXCLUDE: '(CHANGELOG\.md|node_modules/)'
MARKDOWN_MARKDOWN_LINK_CHECK_CONFIG_FILE: .markdown-link-check.json
MARKDOWN_MARKDOWN_LINK_CHECK_CLI_LINT_MODE: file
MARKDOWN_MARKDOWN_TABLE_FORMATTER_FILTER_REGEX_EXCLUDE: '(CHANGELOG\.md|.*AUDIT.*\.md|.*SUMMARY.*\.md)'

# Repository linters
REPOSITORY_CHECKOV_ARGUMENTS: "--framework github_actions --skip-check CKV_GHA_7,CKV2_GHA_1"
REPOSITORY_DEVSKIM_ARGUMENTS: "--ignore-globs **/node_modules/**,**/.git/**"
REPOSITORY_GITLEAKS_CONFIG_FILE: .gitleaks.toml
REPOSITORY_SECRETLINT_ARGUMENTS: "--secretlintrc .secretlintrc.json"
REPOSITORY_TRIVY_ARGUMENTS: "--skip-dirs node_modules"

# YAML settings
YAML_YAMLLINT_CONFIG_FILE: .yamllint.yml

# File exclusions
FILTER_REGEX_EXCLUDE: '(node_modules/|\.git/|\.vscode/|Scripts/.*\.ps1|cache/)'

# Reporting
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
GITHUB_COMMENT_REPORTER: true
JSON_REPORTER: true
MARKDOWN_SUMMARY_REPORTER: true
TAP_REPORTER: false
UPDATED_SOURCES_REPORTER: false

# Parallel execution
PARALLEL: true

# Fail settings
DISABLE_ERRORS: false
FAIL_IF_MISSING_LINTER_IN_FLAVOR: false

# Pre/post commands
PRE_COMMANDS:
  - command: echo "Starting MegaLinter for Prettier-Plugin-Powershell"
    cwd: workspace

POST_COMMANDS:
  - command: echo "MegaLinter complete"
    cwd: workspace
